    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		    		<div align=\"center\">
<table width=\"95%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"table\">
<tr>
<td colspan=\"2\" align=\"center\" class=\"subHeader\" style=\"border-top:none;\" >Rules</td>
</tr>
<tr><td>


    		    		    		    		    		<div style=\"padding-left:15px;padding-rigth:0px;\" align=\"left\"><p><strong>Bleach-RPG Rules and Regulations</strong><br />
    <br />
  These rules and regulations are subject to change at any time, it is the users  own responsibility to ensure they abide by these rules, to avoid punishment.  Ignorance is not an excuse.<br />
  <br />
  <u>-  Offensive language / names.</u><br />
  Minor cursing can be overlooked, however heavy cursing and offending other users (see  harassment) is not allowed. Penalties will be handed out at the  staff\'s discretion.<br />
  <br />
  Offensive language will receive at a maximum of two  warnings. Warnings will be handed out through PM and/or  in posts in the tavern the offense is occurring. Offenders can expect  up to a one day ban, repeated offenders can expect any ban from two  days to a week and a consecutive tavern bans, should offenses persist.</p>
  <p>Offensive usernames are subject to be banned and  deadlocked on sight. Consciously making an offensive username is  against the rules and will not be tolerated. This can be done at  anytime, so you are heavily advised to not test your luck, because a  Vasto Lord account with an offensive username is no different from a Minion account. Rule of thumb, if you think it <em>might</em> be offensive, it probably is.<br>
    <br>
  Offensive  language / usernames consist:</p>
  <ul type=\"disc\">
  <li>Excessive swearing</li>
  <li>Sexual references</li>
  <li>Racism</li>
  <li>Drug references</li>
  <li>Any other content deemed inappropriate by the staff</li>
</ul>
<p><br />
    <br /><br />
    <u>- Language:</u><br />
    In public discussion areas like the Socialize, any language besides English is strictly prohibited.<br />
    Our moderator team cannot possibly know every language, and as such, cannot moderate any messages in languages they do not understand. To prevent harassment out of the staff\'s control, all other languages are only to be used in private messages.<br><br />

<u>- Harassment</u>:<br />
  Harassment, trolling, or otherwise pestering a user is most obviously not allowed. Bans will be granted after written complaints to moderators /  administrators by the user involved. Valid proof must be submitted to warrant the ban. <br />
  <br />
  Sufficient  proof consists of:</p>
<ul type=\"disc\">
  <li>Copies of private messages, reported by the report feature</li>
  <li>Messages posted in the socialize, reported by the report feature</li>
</ul>
<p>The exact punishment is induced at the discretion of the staff and will depend on the severity of the violation.</p>

<p><u>-  Account Sharing</u><br />
  For your safety, account sharing is explicitly forbidden for all users. If any user is found sharing their password, both users can expect bans of at least 48 hours, and a forced password change. As always, repeated offenses result in increased punishments.</p>

<p><u>-  Impersonating a moderator / Administrator:</u><br />
  Anyone found impersonating moderators / administrators will be banned on sight. This rule extends to usernames with great resemblance to that of a moderator, or usernames implying moderator or admin privileges such as \"4dmin1istrat0r\",\"SiteOwner\" and the likes.</p>
  <p>
  <u>- Account Buying / Selling / Trading / Giving away</u><br />
  Trading, selling, or buying accounts is explicitly <b>forbidden</b>. All accounts involved in this process are subject to bans, and any accounts that actually switch ownership may be permanently removed.

  Giving away accounts also falls under this rule.</p>
  
<p><u>- Bots / Reload scripts</u><br />
	Bots, reload scripts or any type of third party software or script that plays the game for you is disallowed. These things stress out the server.<br />
</p>  
<p><u>- User-pictures:</u><br />
  User-pictures are subject to moderation. Inappropriate user-pictures will be removed on sight, and a warning or ban will be issued. <br />
  <br />
  Inappropriate user-pictures include pictures:</p>
<ul type=\"disc\">
  <li>Of sexual nature</li>
  <li>Containing swear words</li>
  <li>Depicting racism of any kind</li>
  <li>Harassing other users (see harassment)</li>
</ul>
<p>The  administration reserves the right to deem user-pictures inappropriate even when not falling under any of the above categories. The admins have the final say.<br />
    <br />
  Failure to comply can result in bans.<br />
  <br />
  <u>- Changes to user data:</u><br />
  The administration will, under no circumstance, manipulate a users stats on request of the user. <br />
  <br />
  Users asking for stat increases or anything of the sorts are subject to bans.</p>

<p><u>- Ranking-Up</u><br />
  A common issue on the game is people disguising the rank-up link as a tiny url in an attempt to voluntarily level you up. All users are to be held responsible for any actions this may result in, and no excuses will be tolerated. Administrators will <b>not</b> edit your account if you mistakenly click the rank-up link.</p>

<p><u>-  Account responsibility:</u><br />
  The owner of the account is, at all times, responsible for anything that occurs on his/her account. Hackers, little brothers, cats, or mysterious glitches are no excuse. 
The staff would also like to warn you to NOT continously switch places to play the game as it will result in confusion which will influence your account negatively. <br />
  <br />
  <u>- Moderator / Admin positions:</u><br />
  Users are not permitted to ask for staff positions. We have a selection process that does not involve applications, and asking often puts you on the bottom of the list. Additionally, you may be warned or receive a ban for asking about it... so just don\'t do it. Don\'t call us, we\'ll call you.</p>
<p><u>- Inquiring about the staff panels:</u><br />
  Inquiring about the moderator / admin panels is strictly forbidden. Anyone found doing this will receive a ban.<br />
</p>
<p><u>- In game positions:</u><br />
  Users holding a leader position are supossed to be active. This means you need to be online to claim the regen of your race at least twice a week. If you fail to do this and you\'re too strong to be taken down by your own race, you will be removed from your seat forcefully for you will be ruining the game for your side.
Also, it\'s known that an account that will be deleted due to inactiveness, that was holding a position, will glitch the seats. So the administration has no trouble with removing you.<br />
<br />
In addition to this, if it turns out you\'re spamming the leader bot (yamamoto and aizen) over and over again to gain experience: <b> yes, you are abusing a glitch and yes this will result into a ban for a period of time the adminstration deems apropiate. Additional to the above consequences, your stats will be reduced as the administration sees fit.</b>
Also you\'re not allowed to attack the leader or any of the captains if you\'re not above level 20, the consequences will be the same as for any other glitch abuse. In other words: You are to keep to the level caps of fighting (anyone 5 levels above or below you when you\'re below level 20. When Level 20-29 everything in the range of level 20 to level 30. And at last when level 30 or above everything of level 30 or above).
Then one more addition to the rule: Attacking the espada, captain or leader only to delete their orders or annoy the user is considered trolling and it will get you banned.<br />
<br />
</p> 
<p><u>- Bans:</u><br />
  Bans are definitive. Anyone found whining about being banned risks having their ban extended. The proper way to contest a ban is to politely contact a head moderator or administrator. Any user trying to circumvent the ban by use of an alternate account will have their main account\'s ban increased, with the latter accounts being permanently banned or deleted. Besides this deleting your account and creating a new one within the set time limit for your old character\'s ban will result in the ban on your old character being replaced to your new character until you have finished the ban.<br />
</p>
<p><u>-  Account limits:</u><br />
  Each user is allowed to one account. If this limit is exceeded, the newest account(s) will be removed and the main account may receive a (permanent) ban, which will extend to all newer accounts. Deleting an account to create a new one is only allowed when the old account has been fully deleted.<br>
  <br>
<b>If you received a wrongful ban:</b> Send an email to brpgstaff@gmail.com explaining your case, and the staff will look into it.
  <br><br>
  <u>- Spamming the Socialize</u><br>
The Socialize (also known as \'the social\') is supposed to be a user friendly area where the players change exchange opinions, information and ideas. As such, the staff of Bleach-RPG would like to keep it an enjoyable environment. Posts that are deemed spam will be deleted on sight and the poster shall be warned to cease such activity. If the offender fails to comply, they are liable to lose the ability to post. Repeated offenders can expect harsher punishments until the practice stops.<br>
<br>
Spamming includes posts:<br>
- In excessive caps.<br>
- In excessive bold/italic/underline/colors<br>
- Large nonsensical posts that stretch the socialize.<br>
- Blank posts (posts containing no message). <br>
- Posts with faces/symbols only.<br>
- Abusing BBCode of any kind. This includes, but is not limited to, excessive use of the URL code.<br>
<br>
This list is not intended to be all inclusive, so technicalities aren\'t generally a valid defense. If you feel like any punitive action taken against your account is unjust, then message an Administrator or Head Moderator with your case.
<br>
<br>
<u>-Advertisement: </u><br>
Advertising for a different site is strictly forbidden.
The following things can and will be seen as advertisement:<br>
-Posting a link to the site in PM\'s or socialize.<br>
-Asking people for \'help\' regarding your new website and offering them money and/or other bonuses when they do so.<br>
-Luring \"constumors\"(this means users) (ie.Offering them money and/or other bonuses when they join the site).<br>
<br>
Anyone found advertising in any or more of the above described ways will be subject to bans as the staff deems appropiate.
In addition to this, the BRPG socialize is not a substitute for a non-existant or not working socialize on a different website.<br>
<br>
This above list is not intended to be all inclusive, so technicalities aren\'t generally a valid defense. If you feel like any punitive action taken against your account is unjust, then message an Administrator or Head Moderator with your case.
<br>
<br>
<u>- Glitching/Hacking</u><br>
As it would go without saying, exploiting faults in the code and  hacking Bleach-RPG is strictly forbidden. Anyone found doing either can expect the wrath of the administration to fall upon their account.<br>
<br>
Along side of this:<br>
- Inquiring about how to glitch<br>
- Inquiring about how to hack<br>
- Threatening to hack the site<br>
- Withholding information about a glitch<br>
<br>
Is also strictly forbidden. Depending on the severity of the offense, a  user found violating this rule can expect whatever punishment is deemed necessary by the administration.</p>
</div>
<i>
<br>
<br>
*Case-by-case interpretations of the rules are within the jurisdiction of the moderating staff and are not set in stone. Scenarios and consequences include, but are not limited to, those listed above. If you disagree with a moderator\'s handling of a situation, alert a Head Mod or Admin; it is not and never will be an excuse for inappropriate conduct or rudeness on your part. 
<br>
<br>
**If you are a repeated offender - your account is liable to be permanently banned. We understand people make mistakes, but people are also expected to learn from their \"mistakes\"
<br><br>
***This site expects its users to conduct themselves in accordance with the rules of fair play and good sportsmanship. Inappropriate behavior not outlined in the specifications above, e.g. alt-killing, botting, and scamming, will not be tolerated. Penalties may range anywhere from a warning, to an extended ban and stat reductions, to permanent bans, at the staff\'s discretion. You participate in questionable practices and activity at your own risk, and are subject to the consequences of your actions.
<br><br>
****You can contact the Administration by sending an email to brpgstaff@gmail.com. Please only use this for important queries, and not for suggestions. Thank You!
</i>
</td></tr>
</table>
</div>