    		<div align=\"center\">
<table width=\"95%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"table\">
<tr>
<td colspan=\"2\" align=\"center\" class=\"subHeader\" style=\"border-top:none;\" >Terms Of Service</td>
</tr>
<tr><td>


    		    		    		    		    		<div style=\"padding-left:15px;padding-rigth:0px;\" align=\"left\"><p><strong>Terms of Service</strong><br />
<b><u>Disclaimer</u></b><br />
Bleach-RPG.com is just a fan site, we did not create the Bleach series nor any other series that may be listed on Bleach-RPG.com, nor did we have any part in the production process. This site is not meant to infringe any of the copyrights, it is simply here to encourage the continuing popularity of Japanese Animation, and for many more young viewers to watch it.
<br /><br />
In no event will Bleach-RPG.com, its host, and any other companies and/or sites linked to Bleach-RPG.com be liable to any party for any direct, indirect, special or other consequential damages for any use of this website, or on any other hyperlinked website, including, without limitation, any lost profits, loss of programs or other data on your information handling system or otherwise, even if we are expressly advised of the possibility of such damages.

<br /><br />
Bleach-RPG accepts no responsibility for the actions of its members i.e. Self harm, Vandalism, Suicide, Homicide, Genocide, Drug abuse, Changes in sexual orientation, Bestiality. Bleach-RPG will not be held responsible and does not encourage any of the above actions or any other form of anti social behaviour. Although Bleach-RPG is highly addictive we encourage you to spend time with your family and loved ones, do not forget them. Remember Bleach-RPG is just a game!
<br /><br />
The Terms of Service can be changed at any time. A major change to these Terms of Service will be announced but it is the responsibility of the player to be aware of and comply to these Terms of Service at all times. Failure to be in compliance with these Terms of Service may result in the immediate deletion of your account.
<br /><br />
Any action within your account you are responsible for. This includes posting an illegal/offensive picture within your account and all message board postings and information exchanged in chat.
<br /><br />
Every player must respect every other player and individual in society. You must not discriminate against someone because of his or her age, gender, skin color, sexual preference, religion or personal beliefs. Any player found to be actively discriminating against another player or member of society in any way, will have their accounts terminated and further action may be taken. This includes, without limitation, character name, message board posts and chat rooms.
<br /><br />
Bleach-RPG encourages and allows users to post and/or exchange opinions, information, and ideas. Please be advised that these player generated opinions, information and ideas do not necessarily reflect the views of Bleach-RPG. While we occasionally do monitor player generated content, in no event does Bleach-RPG assume or have any responsibility or liability for any of this content or for any claims, damages or losses resulting from their use and/or appearance on or in conjunction with this Site or elsewhere. Users remain individually responsible for their ideas, messages and opinions. However, Bleach-RPG still has the right to modify/delete and refuse to post any player generated content that violates these Terms and Conditions. We can also remove the privileges of the users that violate these Terms and Conditions.
<br /><br />
Donations and/or payments of any sort made to Bleach-RPG towards running and maintenance costs and/or any other premium features made through an online vendor are non-refundable.
<br /><br />
Bleach-RPG does not guarantee or make any representations regarding the use or the results of donating/paying through sites such as paypal with regard to their correctness, accuracy, reliability or otherwise. The entire risk is carried by you (i.e. not Bleach-RPG). You assume the complete cost of any necessary servicing, repair or correction.
<br /><br />
Players agree not to, through software or other methods, interfere with the site operation and page content. Players agree to follow all administrator requests and instructions.
<br /><br />
Other sections of the game may have it\\\"s own rules (such as the forums.) These rules are an addition to the Terms of Service and not a replacement. Violation of these rules is considered to be a violation of the Terms of Service and will be dealt with accordingly. Please make yourself familiar with all game rules before playing. Failure to be familiar with the game rules is not an excuse for breaking them and will not be accepted as a defense of your account.
<br /><br />
Bleach-RPG does not guarantee or make any representations regarding the use or the results of the use of the materials within this site with regard to their correctness, accuracy, reliability or otherwise. The entire risk is carried by you (i.e. not Bleach-RPG). You assume the complete cost of any necessary servicing, repair or correction.
<br /><br />
To the fullest extent permissible pursuant to applicable law, Bleach-RPG, It\\\"s Affiliates, and their respective officers, directors, agents, employees, licensors, representatives and third part providers to this site will not be liable for damages of any kind including, without limitation, incidental, indirect, special, consequential, compensatory or any similar damages, that may result from the use of, or the inability to use, the materials contained on this site, whether the material is supplied by Bleach-RPG or any third party.
<br /><br />
Not withstanding the foregoing, in no event shall Bleach-RPG have any liability to you for any claims, damages, losses, and causes of action (whether in contract, tort or otherwise).
<br /><br />
Any individual who attempts to hack, gain unauthorized entry, reverse engineer or affect the system integrity of Bleach-RPG (including attempting to access any internal part of the game from an offsite location) will be dealt with to the fullest extent of the law.
<br /><br />
Any uploaded files, be it pictures or text files and mail sent or received are not the responsibility of Bleach-RPG, but responsibility of the player that uploaded the file or sent the mail.
<br /><br />
Bleach-RPG takes no responsibility for content published by users of this site.
<br /><br /></div>

</td></tr>
</table>
</div>